version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.3
        FRANKENPHP_VERSION: latest
        COMPOSER_VERSION: latest
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:UpMO/rcpg2P5C5etcrr4P70rMN9ORhODC7dF2jZ4tPM=
      APP_DEBUG: 'true'
      APP_TIMEZONE: UTC
      APP_URL: http://localhost
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      APP_FAKER_LOCALE: en_US
      APP_MAINTENANCE_DRIVER: file
      BCRYPT_ROUNDS: 12
      LOG_CHANNEL: stack
      LOG_STACK: single
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug
      DB_CONNECTION: mysql
      DB_HOST: localhost
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root_secret
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      SESSION_ENCRYPT: false
      SESSION_PATH: /
      SESSION_DOMAIN: null
      BROADCAST_CONNECTION: log
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: database
      CACHE_STORE: file
      CACHE_PREFIX: ''
      MEMCACHED_HOST: memcached
      REDIS_CLIENT: phpredis
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      MAIL_MAILER: log
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 2525
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: "hello@example.com"
      MAIL_FROM_NAME: "${APP_NAME}"
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET: ''
      AWS_USE_PATH_STYLE_ENDPOINT: false
      VITE_APP_NAME: "${APP_NAME}"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    develop:
      watch:
        - action: sync
          path: ./
          target: /var/www/html
          ignore:
            - node_modules/
            - vendor/
        - action: sync+restart
          path: composer-*.json
          target: /var/www/html/composer-*.json
    ports:
      - "8080:8000"
    depends_on:
      - db
      - redis
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel
    #   MYSQL_USER: root
      MYSQL_PASSWORD: root_secret
      MYSQL_ROOT_PASSWORD: root_secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge














